### ISSUE TITLE
接口访问不了了，可有解决方法

### ISSUE THREAD

**Issue by Cregin** [JxbSir/YiYuanYunGou#1]
error: Illegal request.

**Comment by JxbSir** [comment]
模拟安卓即可，需要设置header

发自我的 iPhone

**Comment by Cregin** [comment]
header第三个值怎么算的呢

Peter Jin notifications@github.com于2015年5月5日星期二写道：

> 模拟安卓即可，需要设置header
> 
> 发自我的 iPhone
> 
> > 在 2015年5月5日，13:58，lzyroot <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> 写道：
> > 
> > error: Illegal request.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JxbSir/YiYuanYunGou/issues/1#issuecomment-99036209.

## 

发自移动版 Gmail

**Comment by xmagicbox** [comment]
兄弟，如果不能用它的api接口，就只有自己弄一个后台了吧。。。

**Comment by zhenfenyan** [comment]
怎么设置header,我想看IOS版的运行效果

**Comment by JxbSir** [comment]
关于接口由于版权问题，我就不做公开，大家可以看看代码
