### ISSUE TITLE
如何通过审核呢

### ISSUE THREAD

**Issue by jimmymi** [JxbSir/YiYuanYunGou#4]
弱弱的问下，做这个云购如何做才能通过苹果审核呢？

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by JxbSir** [comment]
@jimmymi 当年我上架的时候App Store首款，所以没有任何限制，现在可能规则严格很多，这边没有暂时没有建议，谢谢
